# Generated by Django 3.2.5 on 2022-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_myupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myupload',
            name='myfiles',
            field=models.FileField(upload_to='myimages'),
        ),
    ]
