# Generated by Django 3.2.5 on 2022-02-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_alter_myupload_myfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('doj', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('empphoto', models.ImageField(upload_to='empphoto')),
            ],
        ),
    ]
