# Generated by Django 3.2.5 on 2022-02-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(),
        ),
    ]
