# Generated by Django 3.2.5 on 2022-02-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0005_alter_employee_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empphoto',
            field=models.FileField(upload_to='empphoto'),
        ),
    ]
