# Generated by Django 3.2.5 on 2022-02-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0006_alter_employee_empphoto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
