# Generated by Django 3.2.5 on 2022-02-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0007_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
